version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "nuget"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dotnet"
